### ISSUE TITLE
Allow for partial update if same name is given again

### ISSUE THREAD

**Issue by johnkpaul** [inrhythm/our-people#6]
Once running `npm run add-user`, if the name entered has already been created and is on the filesystem, instead of overwriting the file, first read in the existing file, present the existing information in parens and if the input is empty, keep the existing value.

For example, this is how it should work if John K. Paul was entered already with phone number 2677388174. 

```
What is your Name ? John K. Paul
What's your phone number (existing: 267-738-8174) ?
Please enter the gravatar link (existing: "" :-
...
```

**Comment by jimitpatel9** [comment]
Implemented for Phone
For other questions the link is big so does not look good.

**Comment by johnkpaul** [comment]
What do you mean that the link is big? What does not look good?

Thanks.

On Tue, Oct 27, 2015 at 3:30 PM, JIMIT PATEL <notifications@github.com>
wrote:

> Implemented for Phone
> For other questions the link is big so does not look good.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inrhythm/our-people/issues/6#issuecomment-151618302>.
>



-- 

John K. Paul

john@johnkpaul.com / 267-738-8174

<https://htmlsig.com/signatures/01A74Z76/edit>

[image: Twitter]  <https://twitter.com/johnkpaul>[image: Linkedin]
<http://linkedin.com/in/jkpaul>[image: skype]
<http://skype:john.k.paul/?call>

- [x] regular keyboard
- [ ] permission to have typos
